---
title: | 
  | R for cytometry - fcs files
author: |
  Nello Blaser
institute:
  Department of Mathematics, University of Bergen
date: February 2^nd^ 2018
output: 
    beamer_presentation:
        fonttheme: "structurebold"
        includes:
            in_header: header.tex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## fcs file structures

- `flowFrame`: Represents data contained in FCS files. There are three parts:
    1. raw measurements
    2. annotation for the parameters
    3. additional annotation
- `flowSet`: Container of several `flowFrame`s.

## reading fcs files
```{r read-fcs-file, echo = TRUE, message=FALSE, warning=FALSE, fig.height = 3, fig.width = 7}
require(flowCore)
# a sample file
fcsFile <- system.file("extdata", "0877408774.B08", 
                       package="flowCore")

# read fcs file
ff <- read.FCS(fcsFile)
```

## looking at fcs files
```{r fcs-annotation, echo = TRUE, message=FALSE, warning=FALSE, fig.height = 3, fig.width = 7}
# annotation
pData(ff@parameters)
```

## looking at fcs files
```{r fcs-expressions, echo = TRUE, message=FALSE, warning=FALSE, fig.height = 3, fig.width = 7}
# look at data
ff@exprs[1:10, 1:5]
```

## reading multiple fcs files
```{r multiple-fcs-files, echo = TRUE, message=FALSE, warning=FALSE, fig.height = 3, fig.width = 7}
# file location
fcs.loc <- system.file("extdata", 
                       package="flowCore")
files <- paste(fcs.loc, dir(fcs.loc), 
               sep="/")[1:3]

# read fcs files
fset <- read.flowSet(files)
```

## looking at flowSet
```{r summarize-flowSet, echo = TRUE, message=FALSE, warning=FALSE, fig.height = 3, fig.width = 7}
# flowSet
fset

# flowFrame
fset[[1]]@exprs[1:3, 1:5]
```
